### ISSUE TITLE
UE4 on Android, issue with OpenSSL, Party 1.0.3

### ISSUE THREAD

**Issue by davevill** [PlayFab/PlayFabParty#16]
Just wanna leave a heads up for any Unreal dev and for the PlayFab dev team, party won't work with any version of Unreal (openssl crash) because even the latest version 4.23 uses the old OpenSSL 1.0.Xh libraries on android.

However, this can be fixed by updating the libraries manually [see this.](https://dawnarc.com/2019/07/ue4android-ndkopenssl-linking-issues/)

Ideally since unreal it's pretty popular it should use the patched 1.0.x library or even better give us full source so we can link to our needs :).

Cheers

**Comment by MichaelMackendMS** [comment]
Thank you for the heads up! We'll look into it!

**Comment by MichaelMackendMS** [comment]
But FWIW we have not yet started officially supporting UE integrations.

**Comment by davevill** [comment]
Just wondering if anything has changed since then? any plans to support UE4-android in upcoming releases?
