### ISSUE TITLE
READMEs are out of date

### ISSUE THREAD

**Issue by bamatson** [PlayFab/PlayFabParty#28]
Android and iOS README instructions seem to be for v0.6.0 and should be updated to reflect the latest version. I tried swapping `libplayfabxplatcppsdk.a` for `libparty.a` but am running into linker errors (e.g. `Undefined symbol: _PartyGetNetworks`).

**Comment by SahilAshar** [comment]
Closing this issue as stale. Please feel free to open another issue if you run into further issues!
