### ISSUE TITLE
Headers were not updated for version 1.7.6

### ISSUE THREAD

**Issue by mhaider-bitwisealchemy** [PlayFab/PlayFabParty#31]
I downloaded the Android release and attempted to build a project. My build failed with link errors for these symbols:

PartyEndpointSetProperties
PartyEndpointGetProperty
PartyEndpointGetPropertyKeys
PartyDeviceSetProperties
PartyDeviceGetProperty
PartyDeviceGetPropertyKeys
PartyNetworkGetProperty
PartyNetworkGetPropertyKeys
PartyNetworkSetProperties
PartyChatControlSetProperties
PartyChatControlGetProperty
PartyChatControlGetPropertyKeys

As far as I can tell these functions were removed from the shared library, and the headers were meant to be updated with their replacements.

**Comment by raymondchams** [comment]
Hi,

Thank you for the heads up!
We updated those header files.
Feel free to ask any questions.

Best Regards
