### ISSUE TITLE
Android sample compiled error

### ISSUE THREAD

**Issue by MineloaderGuo** [PlayFab/PlayFabParty#50]
Excuse me, why did I follow the step-by-step steps when compiling PlayFabParty 1.8.0 Android sample, and finally compile an error: PlayFabParty 1.8.0/android/PartySampleNetworkCommon/lib/PlayFabManager. cpp: 0: error: undefined reference to 'PlayFabInternal:: PlayFabSettings:: titleId'?

**Comment by nassosterz-ms** [comment]
Hello.

Thank you for reporting this and apologies for the inconvenience. We will try to provide a status update asap.

**Comment by SahilAshar** [comment]
Hi @MineloaderGuo, thanks again for bringing this to our attention. We've located the build failures and will rolling out a fix soon. Our ETA is hopefully in the next two weeks, but I'll keep you updated. Please let me know if you have any questions in the meantime!

**Comment by SahilAshar** [comment]
Hi @MineloaderGuo - thanks again for your patience. I've just rolled out a large update to our Android PartySample in #52, and just cut a fresh release of PlayFab Party for Android in v1.8.10. These should fix your issues - please let me know if you run into any further trouble.
