### ISSUE TITLE
WSL remark unclear

### ISSUE THREAD

**Issue by mgrichardvanharten** [PlayFab/PlayFabParty#55]
Hi,

Just saw the update to the readme about Party on WSL, it is unclear what "to take advantage of all Party features" means can you add some elaboration as to what will work and what not on WSL? 

Thanks

Richard

**Comment by SebastianPD** [comment]
The networking features of party will work while the chat features will not. WSL does not have built in support for sound.

**Comment by SahilAshar** [comment]
Closing this issue - please feel free to open a new one if you continue to have problems!

**Comment by SahilAshar** [comment]
Closing this issue - please feel free to open a new one if there's something else we can help you with!
